Use-FastAsyncWorldEdit-When-Possible: true
Load-Delay-Ticks: 10
Empty-Chunk-Generator: false
Check-For-Updates: true
use-UUID: false
use-Vault: false
String-Coins: 2000
Coins-Per-Kill: 2
Coins-Per-Win: 50
Min-Exp-Per-Kill: 2
Max-Exp-Per-Kill: 5
Celebration-Length: 10
Max-Warnings: 3
Block-Behind-Signs: 159
Leave-Countdown-Seconds: 5
Party-Invitation-Length: 30
Same-Player-Kill-Limit-Per-Arena: 15
Holograms-Above-Generators: false
Respawn-With-Kit: false
Void-Instant-Death: false
Allow-Spectators-Inventory-View: true
Load-Skins-On-Skulls: true
Disable-Natural-Mob-Spawning: true
Show-Health-On-Bow-Hit: true
Spectators-Chat: true
Team-Chat: true
Lobby-Chat: true
Fireworks-Enabled: true
Leash-Mobs: false
Lobby-Scoreboard: true
Display-Rank-In-Chat: true
Allow-Spectator-Join: true
Show-Health-Below-Name: true
Use-Gamemode-3-For-Spectators: true
Selling-Value: 0.33
Max-Arena-Size: 4500000
Update-Leaderboard-Every-Minutes: 15
Core-Block-Type: DRAGON_EGG
Villager-Shop-Type: Single-Inventory
Teleport-Sound-Enabled: true
Building-Sound-Enabled: true
Build-Protection-Range: 3
Respawn-Duration: 5
Default-Kit: NONE
Dropped-Items-On-Death:
  clear: true
  exceptions:
  - EMERALD
  - DIAMOND
  - GOLD_INGOT
Death-Protection-In-Seconds: 3
Coins-Per-Egg-Break: 15
Generator-Ticking-Speed: 10
Broadcaster-Send-Every: 60
Broadcast-Time:
- 60
- 30
- 15
- 5
- 4
- 3
- 2
- 1
Allowed-Commands:
- ew
- eggwars
- tell
- help
- r
- msg
- ban
- kick
- report
Command-Aliases: []
Mystery-Box:
  Block-Type: ENDER_CHEST
  Cost: 1000
  Contents:
  - 'Kits : 30%'
  - 'Trails : 35%'
  - 'Jaulas : 35%'
  Rarities:
  - 'Común : 60%'
  - 'Raro : 30%'
  - 'Legendario : 10%'
Party:
  Default-Slots: 3
  Custom-Slots:
  - '4 : eggwars.party.slots.4'
  - '5 : eggwars.party.slots.5'
  - '6 : eggwars.party.slots.6'
Bungee-Mode:
  enabled: false
  hub: lobby
  restart-command: restart
MySQL:
  enabled: false
  table: Eggwars
  host: localhost
  port: 3306
  database: database
  username: root
  password: root
  max_uuid_size: 36
  query-url-properties: ''
Rollback:
  Scan-Speed: 50000
  Repair-Speed: 10000
  Queue-Size: 1
  Send-Status-Update-Every: 20
Ranks:
  First-Rank-Exp: 20
  Rank-Modifier: 1.3
  Max-Rank: 30
  Commands:
  - '30 : broadcast %player% acaba de alcanzar el rango más alto!'
Hotbar-Items:
  Arena-Selector:
    enabled: true
    slot: 1
  Shop:
    enabled: true
    slot: 2
  Party:
    enabled: true
    slot: 3
  Boosters:
    enabled: true
    slot: 4
  Profile:
    enabled: true
    slot: 5
  Quit:
    enabled: true
    slot: 9
Arena-Hotbar-Items:
  Team-Selector:
    enabled: true
    slot: 1
  Settings-Vote:
    enabled: true
    slot: 2
  Inventory:
    enabled: true
    slot: 3
  Profile:
    enabled: true
    slot: 5
  Shop:
    enabled: true
    slot: 6
  Quit:
    enabled: true
    slot: 9
Killstreaks:
- '3 : give %player% beef 1'
- '5 : give %player% emerald 1'
- '8 : give %player% golden_apple 1'
- '12 : give %player% emerald 3'
Generator-Settings:
  IRON_INGOT:
    Item-Limit: -1
    Upgrades:
      Enabled: true
      Fix-Cost: 'EMERALD : 1'
      List:
      - 'IRON_INGOT : 48 :: 10'
  GOLD_INGOT:
    Item-Limit: -1
    Upgrades:
      Enabled: true
      Fix-Cost: 'EMERALD : 2'
      List:
      - 'GOLD_INGOT : 32 :: 80'
      - 'GOLD_INGOT : 48 :: 60'
      - 'GOLD_INGOT : 72 :: 40'
  DIAMOND:
    Item-Limit: -1
    Upgrades:
      Enabled: true
      Fix-Cost: 'EMERALD : 3'
      List:
      - 'DIAMOND : 5 :: 160'
      - 'DIAMOND : 15 :: 120'
      - 'DIAMOND : 25 :: 100'
Executed-Commands:
  Player-Win: []
  Arena-Countdown:
  - broadcast La arena %arena% comenzará en %seconds% segundos!
  Egg-Destroy: []
  Arena-Start: []
  Arena-End: []
Respawn-Potion-Effects:
- 'BLINDNESS : 2 : 2'
- 'DAMAGE_RESISTANCE : 3 : 1000'
Saving-Task:
  Enabled: true
  Save-Every-Minutes: 10
Scoreboard-Title-Animation:
  enabled: false
  interval: 8
  frames:
  - '&b&lEGGWARS'
  - '&e&lEGGWARS'
  - '&b&lEGGWARS'
  - '&a&lEGGWARS'
  - '&b&lEGGWARS'
  - '&c&lEGGWARS'
  - '&e&lE&b&lGGWARS'
  - '&b&lE&e&lG&b&lGWARS'
  - '&b&lEG&e&lG&b&lWARS'
  - '&b&lEGG&e&lW&b&lARS'
  - '&b&lEGGW&e&lA&b&lRS'
  - '&b&lEGGWA&e&lR&b&lS'
  - '&b&lEGGWAR&e&lS'
Action-Bar-Enabled: true
Titles-Enabled: true
Voting-Options:
  Time:
    enabled: true
    item: 'WATCH : name:&bTiempo'
    options:
    - '&eAmanecer : 0'
    - '&6Medio día : 2000'
    - '&dAtardecer : 12000'
    - '&3Media noche : 15000'
  Chests:
    enabled: true
    item: 'CHEST : name:&eCofres'
  Health:
    enabled: true
    item: 'APPLE : name:&cSalud'
    options:
    - '&c10 Hearts : 10'
    - '&e20 Hearts : 20'
    - '&630 Hearts : 30'
Custom-Maps:
  Winner-Map:
    enabled: true
    texts:
    - Felicidades
    - '   por ganar!!!'
    image: https://i.imgur.com/FrgIjmJ.png
Play-Again-Message:
  enabled: true
  header: '&b&m---------&e Eggwars &b&m---------'
  content:
  - ' '
  - '         &6Clic para volver a jugar!'
  - ' '
  footer: '&b&m---------------------------'
Active-Boosters: []
